"""1-Init migration. Add heroes table

Revision ID: bfcc0c8057fd
Revises:
Create Date: 2025-07-17 19:19:52.887229

"""

import json
import os
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bfcc0c8057fd"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "heroes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False, comment="Имя"),
        sa.Column(
            "powerstats",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Характеристики",
        ),
        sa.Column(
            "biography",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Биография",
        ),
        sa.Column(
            "appearance",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Внешность",
        ),
        sa.Column(
            "work",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Работа",
        ),
        sa.Column(
            "connections",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Связи",
        ),
        sa.Column(
            "image",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Ссылка на изображение",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("heroes_pkey")),
    )
    op.create_index(op.f("heroes_name_idx"), "heroes", ["name"], unique=False)

    # Загружаем данные героев из фикстуры
    fixtures_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "fixtures")
    heroes_path = os.path.join(fixtures_path, "heroes.json")
    with open(file=heroes_path, encoding="utf-8") as json_data:
        heroes_data = json.load(json_data)

        for hero_data in heroes_data["heroes"]:
            op.execute(
                f"""
                INSERT INTO heroes (id, name, powerstats, biography, appearance, work, connections, image)
                VALUES (
                    '{hero_data["id"]}',
                    '{hero_data["name"]}',
                    '{hero_data["powerstats"]}',
                    '{hero_data["biography"]}',
                    '{hero_data["appearance"]}',
                    '{hero_data["work"]}',
                    '{hero_data["connections"]}',
                    '{hero_data["image"]}'
                )
            """
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("heroes_name_idx"), table_name="heroes")
    op.drop_table("heroes")
    # ### end Alembic commands ###
